theme: minima
title: Zahra's Blog
author: Zahra Shahid
email: zashahid45@gmail.com
description: > 
 Latest innovations in tech by Zahra Shahid.

# social links
twitter_username: zahrashahid8 # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/ZahraShahid # DO NOT include the @ character, or else the build will fail!
facebook_username: https://www.facebook.com/zahra.shahid.5623

show_excerpts: true # set to false to remove excerpts on the homepage
